name: Add Item

on:
  repository_dispatch:
    types: [add_item]

jobs:
  add_item:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: npm install
      - name: Add Item
        run: PAYLOAD='${{ toJson(github.event.client_payload) }}' node scripts/add_item.js
      - name: Add, Commit and Push
        run: |
          git config user.name "Github Actions Bot"
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Add item: ${{ github.event.client_payload.link }}"
          git push
